---
- name: play for all hosts
  hosts: all
  become: yes

  tasks:
  - name: Install chrony package
    ansible.builtin.package:
      name: chrony
      state: latest
  
  - name: Enable chronyd daemon
    service:
      name: chronyd
      state: started
      enabled: true