---

- name: play for RHEL hosts
  hosts: all
  become: yes

  tasks:
  - name: Install chrony package
    yum:
      name: chrony
      state: latest
  
  - name: Enable chronyd daemon
    service:
      name: chronyd
      state: started
      enabled: true