---
- name: play for nfs servers
  become: true
  hosts: nfs

  # prompts for config
  vars_prompt:
    - name: "vg_name"
      prompt: "Enter the name of the volume group here"
      private: no

    - name: "lv1_name"
      prompt: "Enter the name of the first logical volume here"
      private: no
    
    - name: "lv2_name"
      prompt: "Enter the name of the second logical volume here"
      private: no

    - name: "lv3_name"
      prompt: "Enter the name of the third logical volume here"
      private: no

    - name: "lv_size"
      prompt: "Enter the size of the logical volume here"
      private: no
    
    - name: "fs"
      prompt: "Enter the type of filesystem to format logical volumes with"
      private: no

  roles:
    - nfs