---
- name: remove nginx default server directive in nginx.conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^listen       80'
    line: listen       80;
  
- name: configure nginx loadbalancing
  ansible.builtin.template:
    src: ../../templates/loadbalancer.j2
    dest: /etc/nginx/conf.d/loadbalancer.conf
    owner: root
    group: root
    mode: '0644'
  notify: (Handler) Restart Nginx

- name: Flush handlers
  meta: flush_handlers