---
# tasks file for letsencrypt
- name: play for letsencrypt 
  include_vars: "{{ ansible_os_family }}.yml"
   
  # tasks:
  # - name : Install Python Package
  #   yum: 
  #     name: python3 
  #     update_cache: yes 
  #     state: latest
 
  # - name : Install Let's Encrypt Package
  #   yum: 
  #     name: "{{ certbot_package }}"
  #     update_cache: yes 
  #     state: latest
 
  # - name: Create and Install Cert Using {{ certbot_plugin }} Plugin
  #   command: "certbot --{{ certbot_plugin }} -d  {{ certbot_site_names[inventory_hostname_short] }} -m {{ certbot_mail_address }} --agree-tos --noninteractive --redirect"
 
   
  # - name: Set Letsencrypt Cronjob for Certificate Auto Renewal
  #   cron: name=letsencrypt_renewal special_time=monthly job="/usr/bin/certbot renew"
  #   when: ansible_facts['os_family'] == "RedHat"