---
- name: Ensure EPEL repo is added
  package:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"
    enablerepo: "{{ apache_enablerepo | default(omit, true) }}"

# too static !
- name: Install the nginx rpm from a remote repo
  dnf:
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm'
    state: present

- name: Upgrade all packages
  dnf:
    name: '*'
    state: latest

- name: Install snapd
  dnf:
    name: snapd
    state: present

- name: enable snapd
  service:
    name: snapd.socket
    state: started
    enabled: yes

- name: Create a symbolic link for snapd
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    owner: root
    group: root
    state: link
    
- name: Install core
  community.general.snap:
    name:
      - core

- name: Install "certbot" with option --classic
  community.general.snap:
    name: certbot
    classic: yes

- name: Create a symbolic link for certbot
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    owner: root
    group: root
    state: link