---

- name: play for RHEL hosts
  hosts: nfs:webservers:jenkins:lb
  become: yes

  tasks:
  - name: Install chrony package
    yum:
      name: chrony
      state: latest
  
  - name: Enable chronyd daemon
    service:
      name: chronyd
      state: started
      enabled: true

- name: loading play for NFS server(s)
  import_playbook: nfs.yaml