---

- name: Include dynamic variables
  hosts: all

- name: import the common playbook
  import_playbook: ../static-assignments/common.yml
      
    # - name: include the env-vars playbook
    #   include_playbook: ../dynamic-assignments/env-vars.yml
  # tags:
  #   - always

# configure nfs server
# - name: loading play for NFS server(s)
#   hosts: nfs
#   import_playbook: ../static-assignments/nfs.yml

# configure database server
- name: loading play for database server(s)
  import_playbook: ../static-assignments/db.yml

# configure webservers
# - name: Webserver assignment
#   hosts: webservers
#   import_playbook: ../static-assignments/webservers.yml
